### ISSUE TITLE
Can not Cmake for ANN master?

### ISSUE THREAD

**Issue by leoteo1** [michaelquigley/ann#1]
Hello,  I can not build ANN for Visual Studio 2013 X64 by Cmake. Can any one tell me how to make it.

**Comment by michaelquigley** [comment]
This project is a generic cmake project. Check out some sources on how to build a cmake project using Visual Studio:

https://preshing.com/20170511/how-to-build-a-cmake-based-project/

https://dmerej.info/blog/post/cmake-visual-studio-and-the-command-line/
